name: flutter_pax_printer_utility_example_git
description: A new Flutter project example using git dependency.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_pax_printer_utility:
    git:
      url: git@github.com:bazookon/flutter_pax_printer_utility.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true